# Generated by Django 5.1.5 on 2025-01-29 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_base', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Birlik',
                'verbose_name_plural': 'Birliklar',
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umumiy miqdor')),
                ('latest_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Oxirgi sotilish narxi')),
                ('unit', models.ForeignKey(limit_choices_to={'is_base': True}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.unit')),
            ],
            options={
                'verbose_name': "Mahsulot ro'yhati",
                'verbose_name_plural': "Mahsulotlar ro'yhati",
                'db_table': 'products_list',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Umumiy og'irlik")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('products_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='Products.productslist')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='Products.unit')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_conversions', to='Products.unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='Products.unit')),
            ],
            options={
                'verbose_name': 'Birlik konversiyasi',
                'verbose_name_plural': 'Birlik konversiyalari',
                'db_table': 'unit_conversion',
            },
        ),
    ]
