# Generated by Django 5.2 on 2025-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
