# Generated by Django 5.2 on 2025-05-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_orderitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderclient',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderoperator',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
